In [209]:
import numpy as np
import pandas as pd

In [210]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','iq','lpa'])

In [211]:
df.head()

cgpa  iq  lpa
0     8   8    4
1     7   9    5
2     6  10    6
3     5  12    7

In [168]:
def ini_weights(layer_dim):
  parameters = {}
  L = len(layer_dim)

  for i in range(1,L):
    parameters['W' + str(i)] = np.ones((layer_dim[i-1],layer_dim[i]))*0.1
    parameters['b' + str(i)] = np.zeros((layer_dim[i],1))

  return parameters

In [169]:
ini_weights([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [170]:
def linear_forward(W,A_prev,b):

  Z = np.dot(W.T,A_prev) + b

  return Z

In [222]:
def update_weights(parameters,y,y_hat,A1,X):

  parameters['W2'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y-y_hat) * A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y-y_hat) * A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * (y-y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][0][0] * X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y-y_hat) * parameters['W2'][0][0] * X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][1][0] * X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y-y_hat) * parameters['W2'][1][0] * X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y-y_hat) * parameters['W2'][1][0])



In [223]:
def forward_prop(X,parameters):
  A = X;
  l = len(parameters) // 2

  for i in range (1,l+1):
    A_prev = A
    wl = parameters['W' + str(i)]
    bl = parameters['b' + str(i)]

    A = linear_forward(wl,A_prev,bl)

  return A,A_prev


In [224]:
X = df[['cgpa', 'iq']].values[0].reshape(2,1) # Shape(no of features, no. of training example)  2 x 1 matrix is formed
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = ini_weights([2,2,1])

y_hat,A1 = forward_prop(X, parameters)

In [225]:
y_hat = y_hat[0][0]

In [226]:
update_weights(parameters,y,y_hat,A1,X)

In [227]:
y_hat

0.32000000000000006

In [228]:
X = df[['cgpa', 'iq']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = ini_weights([2,2,1])

y_hat,A1 = forward_prop(X,parameters)
y_hat = y_hat[0][0]

update_weights(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [229]:
X = df[['cgpa', 'iq']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[1][0]

# Parameter initialization

y_hat,A1 = forward_prop(X,parameters)
y_hat = y_hat[0][0]

update_weights(parameters,y,y_hat,A1,X)

parameters


{'W1': array([[0.11447776, 0.11673387],
        [0.11481311, 0.11716504]]),
 'b1': array([[0.00195073],
        [0.00199863]]),
 'W2': array([[0.12231605],
        [0.12751067]]),
 'b2': array([[0.01658246]])}

In [230]:
X = df[['cgpa', 'iq']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[2][0]

# Parameter initialization


y_hat,A1 = forward_prop(X,parameters)
y_hat = y_hat[0][0]

update_weights(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.12340367, 0.1316104 ],
        [0.12462942, 0.13352555]]),
 'b1': array([[0.00343838],
        [0.00363469]]),
 'W2': array([[0.13475682],
        [0.14819934]]),
 'b2': array([[0.027622]])}

In [231]:
X = df[['cgpa', 'iq']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[3][0]

# Parameter initializatio

y_hat,A1 = forward_prop(X,parameters)
y_hat = y_hat[0][0]

update_weights(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.13294929, 0.15451988],
        [0.13586939, 0.16050148]]),
 'b1': array([[0.0053475 ],
        [0.00588268]]),
 'W2': array([[0.15028423],
        [0.17695979]]),
 'b2': array([[0.04032542]])}

In [232]:
parameters = ini_weights([2,2,1])
epochs = 5

for i in range(epochs) :

  Loss = []

  for j in range(df.shape[0]):
    X = df[['cgpa', 'iq']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]
    y_hat,A1 = forward_prop(X,parameters)
    y_hat = y_hat[0][0]

    update_weights(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch- ', i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch-  1 Loss -  26.40447639468825
Epoch-  2 Loss -  20.597743519206634
Epoch-  3 Loss -  12.395419753977446
Epoch-  4 Loss -  5.153048486962302
Epoch-  5 Loss -  1.7755704750719727


{'W1': array([[0.24274649, 0.33978913],
        [0.32184489, 0.47836033]]),
 'b1': array([[0.02337812],
        [0.03664327]]),
 'W2': array([[0.25671798],
        [0.55356468]]),
 'b2': array([[0.1291338]])}

In [212]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [213]:
model = Sequential()

model.add(Dense(2,activation = 'linear',input_dim = 2))
model.add(Dense(1,activation = 'linear'))

In [214]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 2)                 6         
                                                                 
 dense_5 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [215]:
model.get_weights()

[array([[ 0.5453299 ,  1.1027006 ],
        [-0.62780625,  1.0133506 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.5950373],
        [-1.1010919]], dtype=float32),
 array([0.], dtype=float32)]

In [216]:
new_weights = [np.array([[0.1, 0.1 ],
        [0.1, 0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [217]:
model.set_weights(new_weights)

In [218]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [219]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'mean_squared_error',optimizer = optimizer)

In [220]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose = 1,batch_size = 1)

Epoch 1/75
4/4 [==============================] - 0s 3ms/step - loss: 27.9075
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 27.5691
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 27.2375
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 26.9288
Epoch 5/75
4/4 [==============================] - 0s 4ms/step - loss: 26.5671
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 26.1957
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 25.8578
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 25.4641
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 25.0804
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6672
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 24.2690
Epoch 12/75
4/4 [==============================] - 0s 4ms/step - loss: 23.8219
Epoch 13/75
4/4 [==============================] - 0s 4ms/ste

In [221]:
model.get_weights()

[array([[0.3738765, 0.3738765],
        [0.3656053, 0.3656053]], dtype=float32),
 array([0.2724481, 0.2724481], dtype=float32),
 array([[0.3730357],
        [0.3730357]], dtype=float32),
 array([0.20477416], dtype=float32)]